"use strict";

/* =========================================================
   KRYNET OPEN-IN-APP

   Converts supported web links into their native
   application protocols.

   Works with normal Krynet <a href="..."> elements,
   including links generated by markdown.js.
========================================================= */

/* =========================================================
   HELPERS
========================================================= */

function isHost(url, hosts) {
    const hostname =
        url.hostname.toLowerCase();

    return hosts.some(host => {
        host = host.toLowerCase();

        return (
            hostname === host ||
            hostname.endsWith(`.${host}`)
        );
    });
}

function getPathParts(url) {
    return url.pathname
        .split("/")
        .filter(Boolean);
}

function parseHttpUrl(value) {
    try {
        const url = new URL(value);

        if (
            url.protocol !== "http:" &&
            url.protocol !== "https:"
        ) {
            return null;
        }

        return url;
    } catch {
        return null;
    }
}

/* =========================================================
   SERVICE RULES
========================================================= */

const SERVICES = [
    {
        id: "spotify",

        match(url) {
            if (
                !isHost(url, [
                    "open.spotify.com"
                ])
            ) {
                return false;
            }

            const parts =
                getPathParts(url);

            const offset =
                parts[0]?.startsWith("intl-")
                    ? 1
                    : 0;

            const type =
                parts[offset];

            const id =
                parts[offset + 1];

            return Boolean(
                type &&
                id &&
                [
                    "track",
                    "album",
                    "artist",
                    "playlist",
                    "user",
                    "episode",
                    "prerelease"
                ].includes(type)
            );
        },

        transform(url) {
            const parts =
                getPathParts(url);

            const offset =
                parts[0]?.startsWith("intl-")
                    ? 1
                    : 0;

            return (
                `spotify://${parts[offset]}/` +
                `${parts[offset + 1]}`
            );
        }
    },

    {
        id: "steam",

        match(url) {
            return isHost(url, [
                "steamcommunity.com",
                "store.steampowered.com"
            ]);
        },

        transform(url) {
            return (
                `steam://openurl/` +
                `${url.href}`
            );
        }
    },

    {
        id: "epic",

        match(url) {
            return isHost(url, [
                "store.epicgames.com"
            ]);
        },

        transform(url) {
            const path =
                url.pathname.replace(
                    /^\/+/,
                    ""
                );

            return (
                `com.epicgames.launcher://` +
                `store/${path}`
            );
        }
    },

    {
        id: "tidal",

        match(url) {
            if (
                !isHost(url, [
                    "tidal.com",
                    "listen.tidal.com"
                ])
            ) {
                return false;
            }

            const parts =
                getPathParts(url);

            const offset =
                parts[0] === "browse"
                    ? 1
                    : 0;

            const type =
                parts[offset];

            const id =
                parts[offset + 1];

            if (!type || !id) {
                return false;
            }

            if (
                ![
                    "track",
                    "album",
                    "artist",
                    "playlist",
                    "user",
                    "video",
                    "mix"
                ].includes(type)
            ) {
                return false;
            }

            return /^[a-f0-9-]+$/i.test(id);
        },

        transform(url) {
            const parts =
                getPathParts(url);

            const offset =
                parts[0] === "browse"
                    ? 1
                    : 0;

            return (
                `tidal://${parts[offset]}/` +
                `${parts[offset + 1]}`
            );
        }
    },

    {
        id: "appleMusic",

        match(url) {
            return isHost(url, [
                "music.apple.com"
            ]);
        },

        transform(url) {
            return url.href.replace(
                /^https:/i,
                "itunes:"
            );
        }
    },

    {
        id: "youtubeMusic",

        match(url) {
            return isHost(url, [
                "music.youtube.com"
            ]);
        },

        transform(url) {
            return (
                `vnd.youtube.music://open?` +
                `url=${encodeURIComponent(
                    url.href
                )}`
            );
        }
    },

    {
        id: "roblox",

        match(url) {
            if (
                !isHost(url, [
                    "roblox.com",
                    "www.roblox.com"
                ])
            ) {
                return false;
            }

            const parts =
                getPathParts(url);

            return (
                parts[0] === "games" &&
                /^\d+$/.test(
                    parts[1] ?? ""
                )
            );
        },

        transform(url) {
            const parts =
                getPathParts(url);

            return (
                `roblox-player://placeId=` +
                `${parts[1]}`
            );
        }
    }
];

/* =========================================================
   URL TRANSFORMATION
========================================================= */

function transformUrl(value) {
    const url =
        parseHttpUrl(value);

    if (!url) {
        return value;
    }

    for (const service of SERVICES) {
        try {
            if (service.match(url)) {
                return service.transform(url);
            }
        } catch {
            /*
             * A bad service rule should never
             * break normal link navigation.
             */
        }
    }

    return value;
}

/* =========================================================
   EXTERNAL OPEN
========================================================= */

function openExternal(
    applicationUrl,
    fallbackUrl
) {
    /*
     * Sciter/Krynet desktop environment.
     */
    try {
        if (
            typeof view !== "undefined" &&
            typeof view.open === "function"
        ) {
            view.open(applicationUrl);
            return;
        }
    } catch {
        // Continue to browser fallback.
    }

    /*
     * Alternative Sciter API.
     */
    try {
        if (
            typeof Sciter !== "undefined" &&
            typeof Sciter.open === "function"
        ) {
            Sciter.open(applicationUrl);
            return;
        }
    } catch {
        // Continue to browser fallback.
    }

    /*
     * Normal browser.
     */
    try {
        window.location.href =
            applicationUrl;

        /*
         * Give the native protocol a chance
         * to be handled by the installed app.
         */
        if (fallbackUrl) {
            window.setTimeout(() => {
                window.open(
                    fallbackUrl,
                    "_blank",
                    "noopener,noreferrer"
                );
            }, 1500);
        }

        return;
    } catch {
        // Final fallback below.
    }

    if (!fallbackUrl) {
        return;
    }

    window.open(
        fallbackUrl,
        "_blank",
        "noopener,noreferrer"
    );
}

/* =========================================================
   CLICK HANDLER
========================================================= */

function handleClick(event) {
    /*
     * Only intercept ordinary left clicks.
     */
    if (
        event.button !== 0 ||
        event.metaKey ||
        event.ctrlKey ||
        event.shiftKey ||
        event.altKey
    ) {
        return;
    }

    const target =
        event.target;

    if (!(target instanceof Element)) {
        return;
    }

    /*
     * Find an anchor even if the user clicked
     * on a <span>, <strong>, image, etc.
     */
    const anchor =
        target.closest("a[href]");

    if (
        !(anchor instanceof HTMLAnchorElement)
    ) {
        return;
    }

    /*
     * Never interfere with downloads.
     */
    if (
        anchor.hasAttribute("download")
    ) {
        return;
    }

    /*
     * Ignore anchors explicitly intended to
     * stay inside the application.
     */
    if (
        anchor.dataset.noAppOpen === "true"
    ) {
        return;
    }

    const originalUrl =
        anchor.href;

    const transformed =
        transformUrl(originalUrl);

    /*
     * Unsupported URL.
     * Let the normal browser behavior happen.
     */
    if (
        transformed === originalUrl
    ) {
        return;
    }

    event.preventDefault();
    event.stopPropagation();

    openExternal(
        transformed,
        originalUrl
    );
}

/* =========================================================
   INITIALIZATION
========================================================= */

let initialized = false;

function initOpenInApp() {
    if (initialized) {
        return;
    }

    initialized = true;

    /*
     * Capture phase means this still works for
     * links generated dynamically by markdown.js.
     */
    document.addEventListener(
        "click",
        handleClick,
        true
    );

    console.log(
        "[Krynet] Open-in-app initialized."
    );
}

/* =========================================================
   AUTO START
========================================================= */

if (
    document.readyState === "loading"
) {
    document.addEventListener(
        "DOMContentLoaded",
        initOpenInApp,
        { once: true }
    );
} else {
    initOpenInApp();
}

/* =========================================================
   PUBLIC API
========================================================= */

export {
    SERVICES,
    transformUrl,
    initOpenInApp
};
